name: Create Linux & Windows Binaries

on:
  workflow_dispatch:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: cargo install -f cross

      - name: Build-linux
        run: cross build --target x86_64-unknown-linux-gnu --release
      - name: Build-win
        run: cross build --target x86_64-pc-windows-gnu --release

      - name: Package Linux
        run: tar -czvf autocref-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-gnu/release/ autocref
      - name: Package Windows
        run: zip -j autocref-windows-x86_64.zip target/x86_64-pc-windows-gnu/release/autocref.exe

      - name: Upload Linux
        uses: actions/upload-artifact@v2
        with:
          name: linux-release
          path: autocref-linux-x86_64.tar.gz
      - name: Uplaod Windows
        uses: actions/upload-artifact@v2
        with:
          name: windows-release
          path: autocref-windows-x86_64.zip
